version: "3"

services:
  # telegram_checker:
    # ...

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data/:/data/db/
    env_file:
      - .env
  
volumes:
  mongo_data:
