version: "3"

services:
  # telegram_checker:
    # ...
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    networks:
      - osint
    ports:
      - 8000:8000
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      - osint
    ports:
      - 27017:27017
    env_file:
      - .env

networks:
  osint:

volumes:
  mongo_data:
