version: "3"

services:
  # telegram_checker:
    # ...
  
  victoria_metrics:
    image: "victoriametrics/victoria-metrics"
    ports:
      - "8428:8428"
    volumes:
      - "vmdata:/victoria-metrics-data"
    env_file: .env
  
volumes:
  vmdata:
