version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    networks:
      - osint
    ports:
      - 8000:8000
    env_file:
      - .env

  tg_scrapper:
    build:
      context: ./tg_scrapper
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    networks:
      - osint
    ports:
      - 8001:8000
    env_file:
      - .env
  
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      - osint
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db/
    env_file:
      - .env

networks:
  osint:

volumes:
  mongo_data:
